"""Research experiment: rational m=4,c=5 local tensors with two equal columns.

No feasibility conclusion is drawn unless exact moment and monotonicity
checks pass.  The remaining equations are a plane cubic; rational points
are generated by its tangent construction.
"""
import json
from itertools import combinations
from math import gcd, lcm, sqrt
from pathlib import Path
import sympy as S
import numpy as np

A, B, W = S.symbols('A B W')
a, b, c, d, z = S.symbols('a b c d z')

def primitive(point):
    den=lcm(*(int(S.denom(x)) for x in point))
    out=[int(x*den) for x in point]
    g=gcd(*out)
    return tuple(x//g for x in out)

def tangent(P, F):
    grad=[S.diff(F,v).subs(dict(zip((A,B,W),P))) for v in (A,B,W)]
    D=None
    for i,j in ((0,1),(0,2),(1,2)):
        vec=[0,0,0];vec[i]=grad[j];vec[j]=-grad[i]
        if any(vec) and S.Matrix([P,vec]).rank()==2:
            D=primitive(vec);break
    if D is None:return None
    poly=S.Poly(F.subs({A:P[0]+z*D[0],B:P[1]+z*D[1],W:P[2]+z*D[2]}),z)
    assert poly.nth(0)==poly.nth(1)==0
    alpha,beta=poly.nth(2),poly.nth(3)
    if beta==0:return primitive(D)
    return primitive([beta*P[i]-alpha*D[i] for i in range(3)])

def experiment(p, trial):
    one=S.ones(5,1); p2=p.applyfunc(lambda x:x*x)
    t=sum(x**3 for x in p)
    sol=next(iter(S.linsolve((S.Matrix([list(one),list(p),list(p2)]),S.Matrix([0,0,-t])))))
    free=sorted(set().union(*(x.free_symbols for x in sol)),key=str)
    assert len(free)==2
    e=S.Matrix(sol).subs(dict(zip(free,(a,b))))
    f=e.subs({a:c,b:d})
    eq=[e.dot(f),sum(p[i]*e[i]*f[i] for i in range(5))-t,
        sum(p[i]**3*(e[i]+f[i])+p[i]**2*e[i]*f[i] for i in range(5))-(1-sum(x**4 for x in p))]
    rows=[]
    for q in eq:
        po=S.Poly(q,c,d)
        rows.append([po.coeff_monomial(c),po.coeff_monomial(d),po.coeff_monomial(1)])
    M=S.Matrix(rows)
    P=S.Poly(M.det(),a,b).clear_denoms()[1].primitive()[1].as_expr()
    # Heuristic real feasibility filter, not a certificate.
    mfun=S.lambdify((a,b),M,'numpy');efun=S.lambdify((a,b),e,'numpy')
    coeff=[S.lambdify(b,S.Poly(P,a).nth(j),'numpy') for j in range(4)]
    pf=np.array(p,dtype=float).ravel();best=(-1e9,None)
    for bb in np.linspace(-.6,.6,2401):
        for aa in np.roots([float(fn(bb)) for fn in reversed(coeff)]):
            if abs(aa.imag)>1e-7:continue
            aa=aa.real;mf=np.array(mfun(aa,bb),dtype=float)
            try:cc,dd=np.linalg.solve(mf[:2,:2],-mf[:2,2])
            except np.linalg.LinAlgError:continue
            ys=[pf+np.array(efun(aa,bb)).ravel(),pf+np.array(efun(cc,dd)).ravel()]
            gap=min(*(np.diff(v).min() for v in ys),*(1-abs(v).max() for v in ys))
            if gap>best[0]:best=(gap,(aa,bb,cc,dd))
    print('real gap heuristic',best,flush=True)
    F=S.Poly(P,a,b).homogenize(W).as_expr().subs({a:A,b:B})
    leading=S.Poly(P,a,b).homogeneous_component(3) if False else S.Poly(F.subs(W,0),A,B)
    factors=S.factor_list(leading.as_expr())[1]
    starts=[]
    for fac,mult in factors:
        if S.Poly(fac,A,B).total_degree()==1:
            fa,fb=S.Poly(fac,A,B).coeff_monomial(A),S.Poly(fac,A,B).coeff_monomial(B)
            starts.append(primitive((fb,-fa,0)))
    print('trial',trial,'cubic bits',max(abs(int(x)).bit_length() for x in S.Poly(F,A,B,W).coeffs()),'starts',len(starts),flush=True)
    for start in starts if best[0]>0 else []:
        point=start
        for step in range(8):
            point=tangent(point,F)
            if point is None:break
            bits=max(abs(x).bit_length() for x in point)
            print('point',step,'bits',bits,flush=True)
            if bits>12000:break
            if point[2]==0:continue
            aa,bb=S.Rational(point[0],point[2]),S.Rational(point[1],point[2])
            solf=S.linsolve((M[:,:2].subs({a:aa,b:bb}),-M[:,2].subs({a:aa,b:bb})))
            if not solf:continue
            cc,dd=next(iter(solf))
            if cc.free_symbols or dd.free_symbols:continue
            ee=e.subs({a:aa,b:bb});ff=f.subs({c:cc,d:dd})
            y=S.Matrix.hstack(p,p,p+ee,p+ff)
            gap=min([y[i+1,j]-y[i,j] for i in range(4) for j in range(4)]+[1-abs(v) for v in y])
            print('gap',float(gap),flush=True)
            if gap<=0:continue
            for k in range(1,5):
                for subset in combinations(range(4),k):
                    target=S.Rational(0) if k%2 else S.Rational(1,k+1)
                    assert sum(S.prod(y[q,j] for j in subset) for q in range(5))/5==target
            print('CERTIFIED LOCAL MODEL',flush=True)
            Path('local_four_on_five_certificate.json').write_text(json.dumps({'y':[[str(y[i,j]) for j in range(4)] for i in range(5)]},indent=2))
            return True
    return False

base=S.Matrix([S.Rational(-5,6),S.Rational(-1,2),S.Rational(1,6),S.Rational(1,2),S.Rational(2,3)])
u=sqrt((5-sqrt(11))/12);v=sqrt((5+sqrt(11))/12)
target=[-v,-u,0,u,v]
for trial,den in enumerate((5,10,20,50,100,200,500)):
    delta=[S.Rational(round(float(base[i]-target[i])*den),den) for i in range(4)]
    delta.append(-sum(delta));delta=S.Matrix(delta)
    if delta.dot(delta)==0:continue
    p=base-2*base.dot(delta)/delta.dot(delta)*delta
    assert sum(p)==0 and p.dot(p)==S.Rational(5,3)
    if experiment(p,trial):break
